
export interface CatalogEntry {
  symbol: string;
  name: string;
  logo: string;
  color: string;
  narrative: string;
  chain: string;
  /** Optional hand-tuned values for the featured tokens shown in the reference design. */
  preset?: { price: number; change24h: number; score: number; risk: number; ageHours: number };
}

export const TOKEN_CATALOG: CatalogEntry[] = [
  { symbol: 'ABC', name: 'ABC Token', logo: '🐸', color: '#22c55e', narrative: 'Frog meta', chain: 'Solana', preset: { price: 0.0012, change24h: 245.6, score: 91, risk: 42, ageHours: 9 } },
  { symbol: 'XYZ', name: 'XYZ Protocol', logo: '🚀', color: '#3b82f6', narrative: 'AI agents', chain: 'Solana', preset: { price: 0.0067, change24h: 182.3, score: 87, risk: 38, ageHours: 20 } },
  { symbol: 'DOGE2', name: 'Doge Two', logo: '🐕', color: '#f59e0b', narrative: 'Dog coins', chain: 'Base', preset: { price: 0.0021, change24h: 98.7, score: 81, risk: 47, ageHours: 60 } },
  { symbol: 'SHIBX', name: 'Shiba X', logo: '🦊', color: '#0ea5e9', narrative: 'Dog coins', chain: 'Ethereum', preset: { price: 0.0045, change24h: 76.1, score: 76, risk: 35, ageHours: 140 } },
  { symbol: 'PEPE', name: 'Pepe Classic', logo: '🐢', color: '#16a34a', narrative: 'Frog meta', chain: 'Ethereum', preset: { price: 0.0008, change24h: 65.4, score: 72, risk: 30, ageHours: 400 } },
  { symbol: 'SOLM', name: 'Sol Moon', logo: '🌙', color: '#8b5cf6', narrative: 'Solana ecosystem', chain: 'Solana', preset: { price: 0.0032, change24h: 52.9, score: 68, risk: 58, ageHours: 30 } },
  { symbol: 'MAGA', name: 'MAGA Coin', logo: '🦅', color: '#ef4444', narrative: 'PolitiFi', chain: 'Ethereum', preset: { price: 0.0019, change24h: 42.7, score: 64, risk: 51, ageHours: 800 } },
  { symbol: 'FROG', name: 'Frog Finance', logo: '🐊', color: '#65a30d', narrative: 'Frog meta', chain: 'Base', preset: { price: 0.0063, change24h: 38.5, score: 62, risk: 33, ageHours: 210 } },
  { symbol: 'BONKZ', name: 'Bonk Zero', logo: '🐶', color: '#f97316', narrative: 'Dog coins', chain: 'Solana' },
  { symbol: 'WIFHAT', name: 'Wif Hat', logo: '🎩', color: '#d946ef', narrative: 'Hat meta', chain: 'Solana' },
  { symbol: 'MOODENG', name: 'Moo Deng', logo: '🦛', color: '#fb7185', narrative: 'Viral animals', chain: 'Solana' },
  { symbol: 'POPCAT', name: 'Popcat', logo: '🐱', color: '#facc15', narrative: 'Cat coins', chain: 'Solana' },
  { symbol: 'TURBO', name: 'Turbo AI', logo: '🤖', color: '#a3e635', narrative: 'AI agents', chain: 'Ethereum' },
  { symbol: 'NEIRO', name: 'Neiro', logo: '🐕‍🦺', color: '#fbbf24', narrative: 'Dog coins', chain: 'Ethereum' },
  { symbol: 'GIGA', name: 'Gigachad', logo: '💪', color: '#94a3b8', narrative: 'Culture', chain: 'Solana' },
  { symbol: 'BRETT', name: 'Brett', logo: '🟦', color: '#2563eb', narrative: 'Base culture', chain: 'Base' },
  { symbol: 'MOG', name: 'Mog Coin', logo: '😼', color: '#f472b6', narrative: 'Cat coins', chain: 'Ethereum' },
  { symbol: 'PONKE', name: 'Ponke', logo: '🐒', color: '#c2410c', narrative: 'Viral animals', chain: 'Solana' },
  { symbol: 'MYRO', name: 'Myro', logo: '🐕', color: '#0891b2', narrative: 'Dog coins', chain: 'Solana' },
  { symbol: 'SLERF', name: 'Slerf', logo: '🦥', color: '#78716c', narrative: 'Viral animals', chain: 'Solana' },
  { symbol: 'BOME', name: 'Book of Meme', logo: '📖', color: '#10b981', narrative: 'Culture', chain: 'Solana' },
  { symbol: 'WEN', name: 'Wen', logo: '⏳', color: '#e879f9', narrative: 'Community', chain: 'Solana' },
  { symbol: 'SAMO', name: 'Samoyed', logo: '🐩', color: '#f8fafc', narrative: 'Dog coins', chain: 'Solana' },
  { symbol: 'CHEEMS', name: 'Cheems', logo: '🍔', color: '#eab308', narrative: 'Dog coins', chain: 'BSC' },
  { symbol: 'KEKW', name: 'Kekw', logo: '😂', color: '#fde047', narrative: 'Culture', chain: 'Base' },
  { symbol: 'HONK', name: 'Honk', logo: '🪿', color: '#fcd34d', narrative: 'Viral animals', chain: 'Solana' },
  { symbol: 'LAMBO', name: 'Lambo Dreams', logo: '🏎️', color: '#dc2626', narrative: 'Culture', chain: 'BSC' },
  { symbol: 'MOONX', name: 'MoonX', logo: '🌕', color: '#cbd5e1', narrative: 'Community', chain: 'BSC' },
  { symbol: 'RKT', name: 'Rocket Cat', logo: '🐈', color: '#fb923c', narrative: 'Cat coins', chain: 'Base' },
  { symbol: 'APU', name: 'Apu Apustaja', logo: '🐸', color: '#4ade80', narrative: 'Frog meta', chain: 'Ethereum' },
  { symbol: 'WOJAK', name: 'Wojak', logo: '😐', color: '#e2e8f0', narrative: 'Culture', chain: 'Ethereum' },
  { symbol: 'CHAD', name: 'Chad Index', logo: '🗿', color: '#a8a29e', narrative: 'Culture', chain: 'Base' },
  { symbol: 'BOBO', name: 'Bobo Bear', logo: '🐻', color: '#b45309', narrative: 'Viral animals', chain: 'Ethereum' },
  { symbol: 'LWOLF', name: 'Landwolf', logo: '🐺', color: '#64748b', narrative: 'Viral animals', chain: 'Base' },
  { symbol: 'PNUT', name: 'Peanut Squirrel', logo: '🐿️', color: '#d97706', narrative: 'Viral animals', chain: 'Solana' },
  { symbol: 'GOAT', name: 'Goatseus', logo: '🐐', color: '#e5e7eb', narrative: 'AI agents', chain: 'Solana' },
  { symbol: 'FWOG', name: 'Fwog', logo: '🐸', color: '#86efac', narrative: 'Frog meta', chain: 'Solana' },
  { symbol: 'MICHI', name: 'Michi', logo: '😺', color: '#fca5a5', narrative: 'Cat coins', chain: 'Solana' },
  { symbol: 'SIGMA', name: 'Sigma', logo: '🐺', color: '#6366f1', narrative: 'Culture', chain: 'Solana' },
  { symbol: 'HAMSTER', name: 'Hamster Wheel', logo: '🐹', color: '#f59e0b', narrative: 'Viral animals', chain: 'BSC' },
  { symbol: 'CATWIF', name: 'Cat Wif Hat', logo: '🐈‍⬛', color: '#a855f7', narrative: 'Hat meta', chain: 'Solana' },
  { symbol: 'BABYD', name: 'Baby Doge X', logo: '🍼', color: '#fbbf24', narrative: 'Dog coins', chain: 'BSC' },
  { symbol: 'FLOKIX', name: 'Floki X', logo: '⚔️', color: '#f97316', narrative: 'Dog coins', chain: 'BSC' },
  { symbol: 'KISHU', name: 'Kishu Inu', logo: '🐕', color: '#fb923c', narrative: 'Dog coins', chain: 'Ethereum' },
  { symbol: 'AKITA', name: 'Akita Inu', logo: '🦮', color: '#f87171', narrative: 'Dog coins', chain: 'Ethereum' },
  { symbol: 'HOGE', name: 'Hoge', logo: '🐷', color: '#f9a8d4', narrative: 'Community', chain: 'Ethereum' },
  { symbol: 'ELON', name: 'Dogelon', logo: '👨‍🚀', color: '#60a5fa', narrative: 'Space', chain: 'Ethereum' },
  { symbol: 'MEOW', name: 'Meow', logo: '🐾', color: '#f0abfc', narrative: 'Cat coins', chain: 'Base' },
  { symbol: 'BARK', name: 'Bark', logo: '🐕', color: '#a16207', narrative: 'Dog coins', chain: 'Base' },
  { symbol: 'QUACK', name: 'Quack', logo: '🦆', color: '#facc15', narrative: 'Viral animals', chain: 'Base' },
  { symbol: 'HIPPO', name: 'Sudeng Hippo', logo: '🦛', color: '#c084fc', narrative: 'Viral animals', chain: 'Solana' },
  { symbol: 'PENGU', name: 'Pengu', logo: '🐧', color: '#38bdf8', narrative: 'NFT culture', chain: 'Solana' },
  { symbol: 'OTTER', name: 'Otter', logo: '🦦', color: '#a78bfa', narrative: 'Viral animals', chain: 'Solana' },
  { symbol: 'KOALA', name: 'Koala', logo: '🐨', color: '#9ca3af', narrative: 'Viral animals', chain: 'Base' },
  { symbol: 'PANDA', name: 'Panda Swap', logo: '🐼', color: '#f5f5f4', narrative: 'Community', chain: 'BSC' },
  { symbol: 'TIGER', name: 'Tiger King', logo: '🐯', color: '#f97316', narrative: 'Viral animals', chain: 'BSC' },
  { symbol: 'SHARK', name: 'Shark Cat', logo: '🦈', color: '#0284c7', narrative: 'Cat coins', chain: 'Solana' },
  { symbol: 'WHALE', name: 'Whale', logo: '🐋', color: '#1d4ed8', narrative: 'Community', chain: 'Solana' },
  { symbol: 'CRAB', name: 'Crab Market', logo: '🦀', color: '#ef4444', narrative: 'Culture', chain: 'Base' },
  { symbol: 'SQUID', name: 'Squid Game', logo: '🦑', color: '#ec4899', narrative: 'Culture', chain: 'BSC' },
  { symbol: 'DEGEN', name: 'Degen', logo: '🎩', color: '#7c3aed', narrative: 'Base culture', chain: 'Base' },
  { symbol: 'TOSHI', name: 'Toshi', logo: '🐱', color: '#3b82f6', narrative: 'Base culture', chain: 'Base' },
  { symbol: 'NUB', name: 'Nubcat', logo: '😿', color: '#94a3b8', narrative: 'Cat coins', chain: 'Solana' },
  { symbol: 'ZEREBRO', name: 'Zerebro', logo: '🧠', color: '#f472b6', narrative: 'AI agents', chain: 'Solana' },
  { symbol: 'FART', name: 'Fartcoin', logo: '💨', color: '#a3e635', narrative: 'Culture', chain: 'Solana' },
  { symbol: 'SPX', name: 'SPX Six', logo: '📈', color: '#22d3ee', narrative: 'Culture', chain: 'Ethereum' },
  { symbol: 'VINE', name: 'Vine Coin', logo: '🍇', color: '#8b5cf6', narrative: 'Culture', chain: 'Solana' },
  { symbol: 'ORBIT', name: 'Orbit Dog', logo: '🛰️', color: '#0ea5e9', narrative: 'Space', chain: 'Solana' },
  { symbol: 'ALIEN', name: 'Alien Base', logo: '👽', color: '#4ade80', narrative: 'Space', chain: 'Base' },
  { symbol: 'BUNNY', name: 'Bunny Hop', logo: '🐰', color: '#fda4af', narrative: 'Viral animals', chain: 'BSC' },
  { symbol: 'NINJA', name: 'Ninja Frog', logo: '🥷', color: '#475569', narrative: 'Frog meta', chain: 'Solana' },
  { symbol: 'PIXEL', name: 'Pixel Pup', logo: '👾', color: '#c026d3', narrative: 'Gaming', chain: 'Base' },
];

/** Fragments used to mint names for simulated new listings. */
export const NEW_LISTING_PARTS = {
  prefixes: ['Baby', 'Mega', 'Super', 'Based', 'Turbo', 'Hyper', 'Tiny', 'Giga', 'Lil', 'Cyber', 'Moon', 'Neo'],
  animals: [
    { word: 'Frog', logo: '🐸' },
    { word: 'Doge', logo: '🐕' },
    { word: 'Cat', logo: '🐱' },
    { word: 'Ape', logo: '🦍' },
    { word: 'Duck', logo: '🦆' },
    { word: 'Panda', logo: '🐼' },
    { word: 'Wolf', logo: '🐺' },
    { word: 'Owl', logo: '🦉' },
    { word: 'Bull', logo: '🐂' },
    { word: 'Robot', logo: '🤖' },
    { word: 'Unicorn', logo: '🦄' },
    { word: 'Dragon', logo: '🐉' },
  ],
  narratives: ['AI agents', 'Frog meta', 'Dog coins', 'Cat coins', 'Viral animals', 'Culture', 'Base culture', 'Gaming'],
  colors: ['#22c55e', '#3b82f6', '#f59e0b', '#ec4899', '#8b5cf6', '#14b8a6', '#f97316', '#eab308'],
};
